# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"W\n\x0b\x45ntityAlias\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nalias_type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\nfirst_seen\x18\x04 \x01(\x03\"g\n\x06\x45ntity\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0e\n\x06is_new\x18\x04 \x01(\x08\x12\x1d\n\x07\x61liases\x18\x05 \x03(\x0b\x32\x0c.EntityAlias\"v\n\x0cRelationship\x12\x13\n\x0bsource_text\x18\x01 \x01(\t\x12\x13\n\x0btarget_text\x18\x02 \x01(\t\x12\x10\n\x08relation\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x16\n\x0e\x64irectionality\x18\x05 \x01(\t\"e\n\rGraphResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x13\n\x0bretry_count\x18\x03 \x01(\x05\x12\x17\n\x0fprocessed_count\x18\x04 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTITYALIAS']._serialized_start=16
  _globals['_ENTITYALIAS']._serialized_end=103
  _globals['_ENTITY']._serialized_start=105
  _globals['_ENTITY']._serialized_end=208
  _globals['_RELATIONSHIP']._serialized_start=210
  _globals['_RELATIONSHIP']._serialized_end=328
  _globals['_GRAPHRESPONSE']._serialized_start=330
  _globals['_GRAPHRESPONSE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
