# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph_messages.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'graph_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14graph_messages.proto\x1a\x0c\x63ommon.proto\"s\n\x12\x41\x64\x64\x45ntitiesRequest\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.Entity\x12\x19\n\x11source_message_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x14\n\x0coperation_id\x18\x04 \x01(\t\"K\n\x13\x41\x64\x64\x45ntitiesResponse\x12 \n\x08response\x18\x01 \x01(\x0b\x32\x0e.GraphResponse\x12\x12\n\nentity_ids\x18\x02 \x03(\t\"\x83\x01\n\x17\x41\x64\x64RelationshipsRequest\x12$\n\rrelationships\x18\x01 \x03(\x0b\x32\r.Relationship\x12\x19\n\x11source_message_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x14\n\x0coperation_id\x18\x04 \x01(\t\"V\n\x18\x41\x64\x64RelationshipsResponse\x12 \n\x08response\x18\x01 \x01(\x0b\x32\x0e.GraphResponse\x12\x18\n\x10relationship_ids\x18\x02 \x03(\t\"S\n\x13GetNeighborsRequest\x12\x13\n\x0b\x65ntity_text\x18\x01 \x01(\t\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\x12\x14\n\x0coperation_id\x18\x03 \x01(\t\"P\n\x14GetNeighborsResponse\x12 \n\x08response\x18\x01 \x01(\x0b\x32\x0e.GraphResponse\x12\x16\n\x0eneighbor_texts\x18\x02 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDENTITIESREQUEST']._serialized_start=38
  _globals['_ADDENTITIESREQUEST']._serialized_end=153
  _globals['_ADDENTITIESRESPONSE']._serialized_start=155
  _globals['_ADDENTITIESRESPONSE']._serialized_end=230
  _globals['_ADDRELATIONSHIPSREQUEST']._serialized_start=233
  _globals['_ADDRELATIONSHIPSREQUEST']._serialized_end=364
  _globals['_ADDRELATIONSHIPSRESPONSE']._serialized_start=366
  _globals['_ADDRELATIONSHIPSRESPONSE']._serialized_end=452
  _globals['_GETNEIGHBORSREQUEST']._serialized_start=454
  _globals['_GETNEIGHBORSREQUEST']._serialized_end=537
  _globals['_GETNEIGHBORSRESPONSE']._serialized_start=539
  _globals['_GETNEIGHBORSRESPONSE']._serialized_end=619
# @@protoc_insertion_point(module_scope)
